config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

    devise_for :users, controllers: {
      confirmations: 'users/confirmations'
    }
 # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"

  resources :users, only: [:index, :show] do
    resources :posts do
      resources :comments, only: [:new, :create]
      resources :likes, only: [ :create, :new]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :save
  after_save :update_comment_counter

  after_destroy :update_comment_counter

  def update_comment_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :save
  after_save :update_like_counter

  def update_like_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def update_post_counter
    author.update(posts_counter: author.posts.count)
  end

  def recent_comment
    comments.order(created_at: :asc).limit(5)
  end

  after_create :save
  after_save :update_post_counter

  after_destroy :update_post_counter
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id

  # validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_create :save

  def recent_posts(limit = 3)
    posts.order(created_at: :desc).limit(limit)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(author_id: current_user.id, post_id: params['post_id'], text: params['text'])

    redirect_to user_post_path(params[:user_id], params[:post_id]) if @comment.save
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create(author_id: current_user.id, post_id: params[:post_id])

    redirect_to user_posts_path(params[:user_id]), notice: 'You added a comment.' if @like.save
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user
  before_action :set_post, only: [:show]

  def index
    @posts = @user.posts
  end

  def show
    @comments = @post.comments
  end

  def new
    @post = Post.new
    @current_user = current_user
  end

  def create
    @post = @user.posts.build(post_params)

    if @post.save
      redirect_to user_post_path(current_user, @post), notice: 'Post created successfully'

    else
      render html 'Error'
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_post
    @post = @user.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = User.new
  end

  def show
    @user = User.includes(:posts, :comments, :likes).find_by(id: params[:id])

    return unless @user.nil?

    render html: 'User not found', status: :not_found
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<main>
  <% if @posts.nil? || @posts.empty? %>
    <h1>There are no posts for this user</h1>
  <% else %>
    <%= render partial: 'shared/user_card', object: @user, as: :user %>

    <h1>Here is the list of posts</h1>

    <% @posts.each do |post| %>

      <%= link_to user_post_path(@user, post.id) do %>
        <%= render partial: 'shared/post_card', locals: { post: post, like: @like } %>
        <div class="comment-card">
          <% post.recent_comment.each do |comment| %>
            <%= render partial: 'shared/comment_card', locals: { comment: comment, model: @comment, url: user_post_comment_path(@user, post, comment) } %>
          <% end %>
        </div>
      <% end %>
    <% end %>
    <%= link_to "Create a Post ", new_user_post_path, class:'add-post' %>
  <% end %>
</main>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with(model: @post, url: user_posts_path(@current_user.id), class: 'flex') do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title, class:'title' %>
  </div>

  <div>
    <%= form.label :text %>
    <%= form.text_area :text, rows:5, class:'text' %>
  </div>

  <%= form.submit 'Create Post', class:'btn' %>
<% end %>

app/views/posts/show.html.erb
<div class='post-show'>

    <h1><%= @post.title %></h1>
    <p><%= @post.text %></p>
    <%= form_with model: @like, url: user_post_likes_path(@post.author_id, @post), method: :post, class: 'btn-container' do |f| %>
      <%= f.button type: :submit, class: 'count btn' do%>
        <%= @post.likes_counter%> Likes
      <% end %>
    <% end%>
    <small>Comments: <%= @post.comments_counter %></small>
    <div class="comment-card">
      <% @post.comments.each do |comment| %>
        <%= render partial: 'shared/comment_card', locals: {comment: comment, url: user_post_comments_path(@user, @post, comment)} %>
      <% end %>
    </div>
    <%= render partial: 'shared/form_comment' %>
</div>

app/views/shared/_comment_card.html.erb
<div class="comment-container">
 <p> <strong><%= comment.author.name %>:</strong><%= comment.text %></p>
</div>

app/views/shared/_form_comment.html.erb
<%= form_with(model: @comment, url: user_post_comments_path(@user.id, @post.id), class:'btn-container-comment', local: true) do |form| %>
<h5> Add Comment</h5>

    <%= form.text_area :text, rows:3, required: true, class:'input' %>


  <%= form.submit 'Add', class:"btn" %>
<% end %>

app/views/shared/_header.html.erb
<header>
 <div >
  <div class="image-contaier">
   <img src=<%= user.photo %> alt=<%= user.name %> id=<%= user.photo %>/>
  </div>
<p> <%= user.name %> </p>
 </div>
</header>

app/views/shared/_post_card.html.erb
<div class="post" id="post-card-<%= post.id %>">
  <h2> <%= post.title %> #<%= post.id %> </h2>
  <p> <%= post.text.slice(0, 150).concat('...') %> </p>
  <small>Comments: <%= post.comments_counter %></small>

  <%= form_with model: @like, url: user_post_likes_path(post.author_id, post), method: :post, class: 'btn-container' do |form| %>
    <%= form.button type: :submit, class:'btn' do %>
      <%= post.likes_counter %> Likes
    <% end %>
  <% end %>

  <%= link_to 'Add Comment', user_post_path(post.author_id, post) %>

</div>

app/views/shared/_user_card.html.erb
<div class="user-card">
  <div class="img-container">

    <img class="user-img" src="<%= user.photo %>" alt="<%= user.name %>" id="<%= user.name %>">
  </div>
  <div class="name-container">
    <h2 class="user-name"><%= user.name %></h2>
    <small class="counter">Number of Posts: <%= user.posts_counter %></small>
  </div>
</div>

app/views/users/index.html.erb
<main>
<h1 class="user-list">List of Users </h1>

 <% @users.limit(4).each do |user| %>
  <%= link_to "/users/#{user.id}" do%>
    <%= render partial: 'shared/user_card', object: user, as: :user %>
  <% end %>
 <% end %>

</main>

app/views/users/show.html.erb
<main>
  <%= render partial: 'shared/user_card', locals: {user: @user} %>
  <article>
    <p>Bio: <%= @user.bio %></p>
  <div class="post-user">
    <small><%= @user.name %>'s posts </small>
  <% @user.posts.limit(3).each do |post|%>
        <%= link_to "/users/#{@user.id}/posts/#{post.id}" do%>
            <%= render partial: 'shared/post_card', locals: {post: post, like: @like}%>
            <div class="comment-card">
                <% post.recent_comment.each do |comment|%>
                <%= render partial:'shared/comment_card', locals: {comment: comment, url: user_post_comment_path(@user, post, comment)} %>
                <% end %>
            </div>
        <% end%>
    <% end %>

    <%= link_to 'See All Posts', user_posts_path(@user), class: 'btn'%>
</main>